apiVersion: v1
kind: Service
metadata:
  name: load-generator
  namespace: crawlers
  labels:
    app: load-generator
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: load-generator
---
apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: crawlers
  labels:
    app: crawler
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: crawler