prometheus:
  server:
    persistentVolume:
      enabled: false
    retention: "2h"
    # Keep a single global block here
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

  serverFiles:
    recording_rules.yml:
      groups:
      - name: proxy_attribution
        rules:
        - record: proxy_requests_total
          expr: |
            label_replace(
              label_replace(
                label_replace(
                  istio_requests_total{source_app="load-generator"},
                  "proxy_vendor", "vendor-a", "destination_service", ".*github.*"
                ),
                "proxy_vendor", "vendor-b", "destination_service", ".*httpbin.*"
              ),
              "proxy_vendor", "vendor-c", "destination_service", ".*typicode.*"
            )
        - record: proxy_request_bytes_sum
          expr: |
            label_replace(
              label_replace(
                label_replace(
                  istio_request_bytes_sum{source_app="load-generator"},
                  "proxy_vendor", "vendor-a", "destination_service", ".*github.*"
                ),
                "proxy_vendor", "vendor-b", "destination_service", ".*httpbin.*"
              ),
              "proxy_vendor", "vendor-c", "destination_service", ".*typicode.*"
            )
        - record: proxy_response_bytes_sum
          expr: |
            label_replace(
              label_replace(
                label_replace(
                  istio_response_bytes_sum{source_app="load-generator"},
                  "proxy_vendor", "vendor-a", "destination_service", ".*github.*"
                ),
                "proxy_vendor", "vendor-b", "destination_service", ".*httpbin.*"
              ),
              "proxy_vendor", "vendor-c", "destination_service", ".*typicode.*"
            )
    prometheus.yml:
      scrape_configs:
        - job_name: 'istio-proxy'
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - crawlers
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_container_name]
              action: keep
              regex: istio-proxy
            - source_labels: [__address__]
              action: replace
              regex: ([^:]+)(?::\d+)?
              replacement: $1:15020
              target_label: __address__
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod_name
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_annotation_proxy_vendor]
              target_label: proxy_vendor

grafana:
  adminPassword: admin
  service:
    type: ClusterIP
    port: 80

  persistence:
    enabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-stack-prometheus-server:80
          access: proxy
          isDefault: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      proxy-usage:
        file: dashboards/proxy-usage.json
