loadGenerator:
  replicas: 2
  image:
    repository: crawler-load-gen
    tag: latest
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  
  config:
    requestRate: 10  # requests per second per pod
    proxies:
      - vendor: vendor-a
        ips: ["10.1.1.1", "10.1.1.2", "10.1.1.3"]
        port: 8080
      - vendor: vendor-b
        ips: ["10.2.1.1", "10.2.1.2"]
        port: 8080
      - vendor: vendor-c
        ips: ["10.3.1.1", "10.3.1.2", "10.3.1.3", "10.3.1.4"]
        port: 8080
    
    destinations:
      - "httpbin.org"
      - "jsonplaceholder.typicode.com"
      - "api.github.com"
      - "httpstat.us"
      - "postman-echo.com"

crawlerPods:
  replicas: 4
  image:
    repository: crawler-pod
    tag: latest
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi